name: doclight
description: A simple image-to-PDF converter designed for document scanning.
# version: 1.0.0
homepage: https://github.com/Quantaly/doclight

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  angular: ^5.3.0
  angular_bloc: ^3.0.0
  angular_components: ^0.13.0
  angular_forms: ^2.1.0
  built_value: ^7.0.0
  http: ^0.12.0
  image: ^2.1.0
  json_rpc_2: ^2.1.0
  pdf: ^1.4.0
  service_worker: ^0.2.0

dev_dependencies:
  angular_test: ^2.3.0
  build_runner: ^1.6.0
  build_test: ^0.10.0
  build_web_compilers: ^2.3.0
  built_value_generator: ^7.0.0
  sass_builder: ^2.1.0
  test: ^1.6.0

  quantaly_lints:
    git:
      url: https://github.com/Quantaly/dart_lints